### ISSUE TITLE
Can simply call user.toJSON()

### ISSUE THREAD

**Issue by 7HUND3RX** [TheJSGirl/playing-with-koa#1]
https://github.com/TheJSGirl/playing-with-koa/blob/0c650219b023225a306334d33c2441e8076a4ce3/src/authentication/middleware.js#L20

**Comment by TheJSGirl** [comment]
Thanks a lot, I went ahead as suggested and fix this. See here: db4de8b36b96ce534a25b6984fb8531919250d1a
